front_cam_pointcloud:
  channels: ['rgb', 'chair','sofa',"person" ]
  fusion: ['color','class_average','class_average','class_average']
  topic_name: 'front_camera/semantic_pointcloud'
  semantic_segmentation: True
  publish_segmentation_image: True
  segmentation_model: 'lraspp_mobilenet_v3_large' # detectron_coco_panoptic_fpn_R_101_3x, lraspp_mobilenet_v3_large
  show_label_legend: False
  data_type: pointcloud

  cam_info_topic: "camera/depth/camera_info"
  image_topic: "camera/rgb/image_raw"
  depth_topic: "camera/depth/image_raw"
  cam_frame: "camera_rgb_optical_frame"

front_cam_image:
  channels: ['chair','sofa',"person"]
  fusion_methods: ['exponential','exponential','exponential']
  publish_topic: 'semantic_image'
  publish_image_topic: "semantic_image_debug"
  publish_camera_info_topic: 'semantic_image_info'
  publish_fusion_info_topic: 'semantic_image_fusion_info'
  data_type: image

  semantic_segmentation: True
  feature_extractor: True
  segmentation_model: 'lraspp_mobilenet_v3_large' # detectron_coco_panoptic_fpn_R_101_3x, lraspp_mobilenet_v3_large
  show_label_legend: False
  image_topic: "camera/rgb/image_raw"
  camera_info_topic: "camera/depth/camera_info"
  resize: 0.5